### ISSUE TITLE
Request for Calibration Codes

### ISSUE THREAD

**Issue by yanrihong** [cage-policy/CAGE#2]
Hello,

I'm currently working with the experimental platform that includes an in-hand camera and several global cameras. I've been referring to the Calibration Guide, but I'm having trouble implementing the calibration steps as I don't have the actual code for the following calibrations:

_1. Hand-Eye Calibration: The guide mentions that the transformation matrix from the in-hand camera to the robot's tool center point (tcp), denoted as INHAND_CAM_TCP, is established through hand-eye calibration techniques and is stored in dataset/constants.py. It also states that this calibration is usually only needed once unless the position of the in-hand camera relative to the robotic arm changes. I would like to have the code that performs this hand-eye calibration so that I can ensure it's done correctly and make any necessary adjustments if needed._

_2. Camera Calibration: For this, we utilize ArUco markers as described. The steps involve moving the robot to a specific pose, printing out the marker, placing it for all cameras to detect, and saving relevant data like the robot's pose and transformation matrices. However, without the actual code that utilizes the opencv-python package's ArUco detector to derive the transformation matrix from the camera to the marker and perform the other necessary operations for this calibration, I'm unable to complete this step accurately._

Could you please provide the code for both of these calibrations? It would be extremely helpful for me to continue my work with the experimental platform.

Thank you!

**Comment by Xiashangning** [comment]
Hi, CAGE is based solely on RGB images. Therefore NO calibration is needed. We have modified the README to clarify that. Thanks!
